version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: git
  abbrev: 7
  format: "[{{ .SHA }}](https://github.com/saesh/hammerhead-go/commit/{{ .SHA }}): {{ .Message }}"
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?\!?:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?\!?:'
      order: 1
    - title: Performance
      regexp: '^perf(\(.+\))?\!?:'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^ci'
      - '^test'
      - Merge pull request
      - Merge branch
